# JWT
jwt:
  header: Authorization
  secret: kiouweflasvbguio
  expiration: 604800
  tokenHead: Bearer
  route:
    authentication:
      path: auth
      refresh: "auth/refresh"
      register: "auth/register"
app:
  datasource:
    mdb:
      url: jdbc:h2:file:~/test
      username: "@db.username@"
      password: "@db.password@"
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

