# JWT
jwt:
  header: Authorization
  secret: kiouweflasvbguio
  expiration: 604800
  tokenHead: Bearer
  route:
    authentication:
      path: auth
      refresh: "auth/refresh"
      register: "auth/register"
app:
  datasource:
    mdb:
      url: jdbc:mysql://localhost:3306/play?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true&useLocalSessionState=true&allowPublicKeyRetrieval=true
      username: ${db.mysql.play.username}
      password: ${db.mysql.play.password}
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 19
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    mydb:
      url: jdbc:sqlserver://localhost:1433;DatabaseName=winds
      username: sa
      password: sqlserver2014
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 19
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: false
#        use_sql_comments: true
#        format_sql: true
#
####
##   H2 Settings
####
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        trace: false
#        web-allow-others: false

